# Site settings
title: Twitter User Behaviour
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/datastory/" # the subpath of your site, e.g. /blog/
url: "https://mariegold.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
