title: (Not) Your Average Twitter User
logo: /assets/img/logo.png
description: Discovering groups of similar Twitter users based on their profiles.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal